// <auto-generated />
using System;
using APBD_dodatkowe_s27062.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APBD_dodatkowe_s27062.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250620192844_Add foreign key to Prelegent_Wydarzenie table for WydarzenieId")]
    partial class AddforeignkeytoPrelegent_WydarzenietableforWydarzenieId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APBD_dodatkowe_s27062.Models.Prelegent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Prelegent");
                });

            modelBuilder.Entity("APBD_dodatkowe_s27062.Models.PrelegentWydarzenie", b =>
                {
                    b.Property<int>("PrelegentId")
                        .HasColumnType("int")
                        .HasColumnName("Prelegent_ID");

                    b.Property<int>("WydarzenieId")
                        .HasColumnType("int")
                        .HasColumnName("Wydarzenie_ID");

                    b.HasKey("PrelegentId", "WydarzenieId");

                    b.HasIndex("WydarzenieId");

                    b.ToTable("Prelegent_Wydarzenie");
                });

            modelBuilder.Entity("APBD_dodatkowe_s27062.Models.Uczestnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Uczestnik");
                });

            modelBuilder.Entity("APBD_dodatkowe_s27062.Models.UczestnikWydarzenie", b =>
                {
                    b.Property<int>("UczestnikId")
                        .HasColumnType("int")
                        .HasColumnName("Uczestnik_ID");

                    b.Property<int>("WydarzenieId")
                        .HasColumnType("int")
                        .HasColumnName("Wydarzenie_ID");

                    b.HasKey("UczestnikId", "WydarzenieId");

                    b.ToTable("Uczestnik_Wydarzenie");
                });

            modelBuilder.Entity("APBD_dodatkowe_s27062.Models.Wydarzenie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxUczestnikow")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Wydarzenie");
                });

            modelBuilder.Entity("APBD_dodatkowe_s27062.Models.PrelegentWydarzenie", b =>
                {
                    b.HasOne("APBD_dodatkowe_s27062.Models.Prelegent", "Prelegent")
                        .WithMany("PrelegenciWydarzenia")
                        .HasForeignKey("PrelegentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_dodatkowe_s27062.Models.Wydarzenie", "Wydarzenie")
                        .WithMany("PrelegenciWydarzenia")
                        .HasForeignKey("WydarzenieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prelegent");

                    b.Navigation("Wydarzenie");
                });

            modelBuilder.Entity("APBD_dodatkowe_s27062.Models.Prelegent", b =>
                {
                    b.Navigation("PrelegenciWydarzenia");
                });

            modelBuilder.Entity("APBD_dodatkowe_s27062.Models.Wydarzenie", b =>
                {
                    b.Navigation("PrelegenciWydarzenia");
                });
#pragma warning restore 612, 618
        }
    }
}
